<?php

use Illuminate\Database\Seeder;

class ServerSeeder extends Seeder {
 public function run() {
  DB::table('efflux_assets.servers')->insertOrIgnore([[
   'id'            => 1,
   'name'          => 'efflux',
   'public_ip'     => '54.183.193.193',
   'private_ip'    => '172.31.17.130',
   'user'          => 'ploi',
   'pass'          => null,
   'sudo_pass'     => 'NGdGaL0klfEOWFeEiMgm',
   'db_user'       => 'ploi',
   'db_pass'       => '1GBvL85xuYYCPYdzcklL',
   'provider'      => 'aws',
   'sys_os'        => 'Ubuntu 18.04 x64',
   'sys_cpus'      => '4',
   'sys_harddrive' => '8GiB',
   'sys_memory'    => '16GiB',
   'notes'         => 't2.xlarge - us-west-1a',
  ], [
   'id'            => 2,
   'name'          => 'dev-efflux',
   'public_ip'     => '45.32.69.220',
   'private_ip'    => null,
   'user'          => 'ploi',
   'pass'          => null,
   'sudo_pass'     => 'uHFIVHf9pH0AQ8tECGYG',
   'db_user'       => 'ploi',
   'db_pass'       => 'HUmpf8mOQBlTU5td9yWf',
   'provider'      => 'vultr',
   'sys_os'        => 'Ubuntu 18.04 x64',
   'sys_cpus'      => '1',
   'sys_harddrive' => '55GiB',
   'sys_memory'    => '2GiB',
   'notes'         => 'Los Angeles',
  ], [
   'id'            => 3,
   'name'          => 'sevenbars',
   'public_ip'     => '54.183.172.60',
   'private_ip'    => '172.31.18.133',
   'user'          => 'ploi',
   'pass'          => null,
   'sudo_pass'     => '1YusvAoCPTP7wnqxYw5q',
   'db_user'       => 'ploi',
   'db_pass'       => 'AZWWJ1NNMrGwBu9dTEWV',
   'provider'      => 'aws',
   'sys_os'        => 'Ubuntu 18.04 x64',
   'sys_cpus'      => '2',
   'sys_harddrive' => '8GiB',
   'sys_memory'    => '8GiB',
   'notes'         => 't2.large - us-west-1a',
  ], [
   'id'            => 4,
   'name'          => 'dev-sevenbars',
   'public_ip'     => '66.42.108.180',
   'private_ip'    => null,
   'user'          => 'ploi',
   'pass'          => null,
   'sudo_pass'     => 'exd3KsmR45unxlUbMeXA',
   'db_user'       => 'ploi',
   'db_pass'       => 'cUjNV5ylxpfnuB6xk3fZ',
   'provider'      => 'vultr',
   'sys_os'        => 'Ubuntu 18.04 x64',
   'sys_cpus'      => '4',
   'sys_harddrive' => '160GiB',
   'sys_memory'    => '8GiB',
   'notes'         => 'Los Angeles',
  ], [
   'id'            => 5,
   'name'          => 'butcherbox.best',
   'public_ip'     => '13.57.177.75',
   'private_ip'    => '172.31.27.53',
   'user'          => 'ploi',
   'pass'          => null,
   'sudo_pass'     => 'kQl1SJsG1kYz2YvIXGMc',
   'db_user'       => 'ploi',
   'db_pass'       => '3QIxLBxvXw7hyj2gmSEg',
   'provider'      => 'aws',
   'sys_os'        => 'Ubuntu 18.04 x64',
   'sys_cpus'      => '2',
   'sys_harddrive' => '8GiB',
   'sys_memory'    => '4GiB',
   'notes'         => 't2.large - us-west-1a',
  ], [
   'id'            => 6,
   'name'          => 'uBot-1',
   'public_ip'     => '144.202.126.98',
   'private_ip'    => null,
   'user'          => 'Administrator',
   'pass'          => 'rK[8BaD_uL}rVKM[',
   'sudo_pass'     => null,
   'db_user'       => null,
   'db_pass'       => null,
   'provider'      => 'vultr',
   'sys_os'        => 'Windows Server 2016',
   'sys_cpus'      => '2',
   'sys_harddrive' => '80GiB',
   'sys_memory'    => '4GiB',
   'notes'         => 'Los Angeles',
  ]]);
  //
 }
}