<?php

use Illuminate\Database\Seeder;

class SitePivotsSeeder extends Seeder {
 public function run() {
  DB::table('efflux_site.post_image')->insertOrIgnore([
   ['id' => 1, 'domain_id' => 3, 'image_id' => 1, 'post_id' => 1, 'page_id' => NULL],
   ['id' => 2, 'domain_id' => 3, 'image_id' => 2, 'post_id' => 2, 'page_id' => NULL],
   ['id' => 3, 'domain_id' => 3, 'image_id' => 3, 'post_id' => 3, 'page_id' => NULL],
   ['id' => 4, 'domain_id' => 3, 'image_id' => 4, 'post_id' => 4, 'page_id' => NULL],
   ['id' => 5, 'domain_id' => 3, 'image_id' => 5, 'post_id' => 5, 'page_id' => NULL],
   ['id' => 6, 'domain_id' => 3, 'image_id' => 6, 'post_id' => 6, 'page_id' => NULL],
   ['id' => 7, 'domain_id' => 3, 'image_id' => 7, 'post_id' => 7, 'page_id' => NULL],
   ['id' => 8, 'domain_id' => 3, 'image_id' => 8, 'post_id' => 8, 'page_id' => NULL],
   ['id' => 9, 'domain_id' => 3, 'image_id' => 9, 'post_id' => 9, 'page_id' => NULL],
   ['id' => 10, 'domain_id' => 3, 'image_id' => 10, 'post_id' => 10, 'page_id' => NULL],
   ['id' => 11, 'domain_id' => 3, 'image_id' => 11, 'post_id' => 11, 'page_id' => NULL],
   ['id' => 12, 'domain_id' => 3, 'image_id' => 12, 'post_id' => 12, 'page_id' => NULL],
   ['id' => 13, 'domain_id' => 3, 'image_id' => 13, 'post_id' => 13, 'page_id' => NULL],
   ['id' => 14, 'domain_id' => 3, 'image_id' => 14, 'post_id' => 14, 'page_id' => NULL],
   ['id' => 15, 'domain_id' => 3, 'image_id' => 15, 'post_id' => 15, 'page_id' => NULL],
   ['id' => 16, 'domain_id' => 3, 'image_id' => 16, 'post_id' => 16, 'page_id' => NULL],
   ['id' => 17, 'domain_id' => 3, 'image_id' => 17, 'post_id' => 17, 'page_id' => NULL],
   ['id' => 18, 'domain_id' => 3, 'image_id' => 18, 'post_id' => 18, 'page_id' => NULL],
   ['id' => 19, 'domain_id' => 3, 'image_id' => 19, 'post_id' => 19, 'page_id' => NULL],
   ['id' => 20, 'domain_id' => 3, 'image_id' => 20, 'post_id' => 20, 'page_id' => NULL],
   ['id' => 21, 'domain_id' => 3, 'image_id' => 21, 'post_id' => 21, 'page_id' => NULL],
   ['id' => 22, 'domain_id' => 3, 'image_id' => 22, 'post_id' => 22, 'page_id' => NULL],
   ['id' => 23, 'domain_id' => 3, 'image_id' => 23, 'post_id' => 23, 'page_id' => NULL],
   ['id' => 24, 'domain_id' => 3, 'image_id' => 24, 'post_id' => 24, 'page_id' => NULL],
   ['id' => 25, 'domain_id' => 3, 'image_id' => 25, 'post_id' => 25, 'page_id' => NULL],
   ['id' => 26, 'domain_id' => 3, 'image_id' => 26, 'post_id' => 26, 'page_id' => NULL],
   ['id' => 27, 'domain_id' => 3, 'image_id' => 27, 'post_id' => 27, 'page_id' => NULL],
   ['id' => 28, 'domain_id' => 3, 'image_id' => 28, 'post_id' => 28, 'page_id' => NULL],
   ['id' => 29, 'domain_id' => 3, 'image_id' => 29, 'post_id' => 29, 'page_id' => NULL],
   ['id' => 30, 'domain_id' => 3, 'image_id' => 30, 'post_id' => 30, 'page_id' => NULL],
   ['id' => 31, 'domain_id' => 3, 'image_id' => 31, 'post_id' => 31, 'page_id' => NULL],
   ['id' => 32, 'domain_id' => 3, 'image_id' => 32, 'post_id' => 32, 'page_id' => NULL],
   ['id' => 33, 'domain_id' => 3, 'image_id' => 33, 'post_id' => 33, 'page_id' => NULL],
   ['id' => 34, 'domain_id' => 3, 'image_id' => 34, 'post_id' => 34, 'page_id' => NULL],
   ['id' => 35, 'domain_id' => 3, 'image_id' => 35, 'post_id' => 35, 'page_id' => NULL],
   ['id' => 36, 'domain_id' => 3, 'image_id' => 36, 'post_id' => 36, 'page_id' => NULL],
   ['id' => 37, 'domain_id' => 3, 'image_id' => 37, 'post_id' => 37, 'page_id' => NULL],
   ['id' => 38, 'domain_id' => 3, 'image_id' => 38, 'post_id' => 38, 'page_id' => NULL],
   ['id' => 39, 'domain_id' => 3, 'image_id' => 39, 'post_id' => 39, 'page_id' => NULL],
   ['id' => 40, 'domain_id' => 3, 'image_id' => 40, 'post_id' => 40, 'page_id' => NULL],
   ['id' => 41, 'domain_id' => 3, 'image_id' => 41, 'post_id' => 41, 'page_id' => NULL],
   ['id' => 42, 'domain_id' => 3, 'image_id' => 42, 'post_id' => 42, 'page_id' => NULL],
   ['id' => 43, 'domain_id' => 3, 'image_id' => 43, 'post_id' => 43, 'page_id' => NULL],
   ['id' => 44, 'domain_id' => 3, 'image_id' => 44, 'post_id' => 44, 'page_id' => NULL],
   ['id' => 45, 'domain_id' => 3, 'image_id' => 45, 'post_id' => 45, 'page_id' => NULL],
   ['id' => 46, 'domain_id' => 3, 'image_id' => 46, 'post_id' => 46, 'page_id' => NULL],
   ['id' => 47, 'domain_id' => 3, 'image_id' => 47, 'post_id' => 47, 'page_id' => NULL],
   ['id' => 48, 'domain_id' => 3, 'image_id' => 48, 'post_id' => 48, 'page_id' => NULL],
   ['id' => 49, 'domain_id' => 3, 'image_id' => 49, 'post_id' => 49, 'page_id' => NULL],
   ['id' => 50, 'domain_id' => 3, 'image_id' => 50, 'post_id' => 50, 'page_id' => NULL],
   ['id' => 51, 'domain_id' => 3, 'image_id' => 51, 'post_id' => 1, 'page_id' => NULL],
   ['id' => 52, 'domain_id' => 3, 'image_id' => 52, 'post_id' => 2, 'page_id' => NULL],
   ['id' => 53, 'domain_id' => 3, 'image_id' => 53, 'post_id' => 3, 'page_id' => NULL],
   ['id' => 54, 'domain_id' => 3, 'image_id' => 54, 'post_id' => 4, 'page_id' => NULL],
   ['id' => 55, 'domain_id' => 3, 'image_id' => 55, 'post_id' => 5, 'page_id' => NULL],
   ['id' => 56, 'domain_id' => 3, 'image_id' => 56, 'post_id' => 6, 'page_id' => NULL],
   ['id' => 57, 'domain_id' => 3, 'image_id' => 57, 'post_id' => 7, 'page_id' => NULL],
   ['id' => 58, 'domain_id' => 3, 'image_id' => 58, 'post_id' => 8, 'page_id' => NULL],
   ['id' => 59, 'domain_id' => 3, 'image_id' => 59, 'post_id' => 9, 'page_id' => NULL],
   ['id' => 60, 'domain_id' => 3, 'image_id' => 60, 'post_id' => 10, 'page_id' => NULL],
   ['id' => 61, 'domain_id' => 3, 'image_id' => 61, 'post_id' => 11, 'page_id' => NULL],
   ['id' => 62, 'domain_id' => 3, 'image_id' => 62, 'post_id' => 12, 'page_id' => NULL],
   ['id' => 63, 'domain_id' => 3, 'image_id' => 63, 'post_id' => 13, 'page_id' => NULL],
   ['id' => 64, 'domain_id' => 3, 'image_id' => 64, 'post_id' => 14, 'page_id' => NULL],
   ['id' => 65, 'domain_id' => 3, 'image_id' => 65, 'post_id' => 15, 'page_id' => NULL],
   ['id' => 66, 'domain_id' => 3, 'image_id' => 66, 'post_id' => 16, 'page_id' => NULL],
   ['id' => 67, 'domain_id' => 3, 'image_id' => 67, 'post_id' => 17, 'page_id' => NULL],
   ['id' => 68, 'domain_id' => 3, 'image_id' => 68, 'post_id' => 18, 'page_id' => NULL],
   ['id' => 69, 'domain_id' => 3, 'image_id' => 69, 'post_id' => 19, 'page_id' => NULL],
   ['id' => 70, 'domain_id' => 3, 'image_id' => 70, 'post_id' => 20, 'page_id' => NULL],
   ['id' => 71, 'domain_id' => 3, 'image_id' => 71, 'post_id' => 21, 'page_id' => NULL],
   ['id' => 72, 'domain_id' => 3, 'image_id' => 72, 'post_id' => 22, 'page_id' => NULL],
   ['id' => 73, 'domain_id' => 3, 'image_id' => 73, 'post_id' => 23, 'page_id' => NULL],
   ['id' => 74, 'domain_id' => 3, 'image_id' => 74, 'post_id' => 24, 'page_id' => NULL],
   ['id' => 75, 'domain_id' => 3, 'image_id' => 75, 'post_id' => 25, 'page_id' => NULL],
   ['id' => 76, 'domain_id' => 3, 'image_id' => 76, 'post_id' => 26, 'page_id' => NULL],
   ['id' => 77, 'domain_id' => 3, 'image_id' => 77, 'post_id' => 27, 'page_id' => NULL],
   ['id' => 78, 'domain_id' => 3, 'image_id' => 78, 'post_id' => 28, 'page_id' => NULL],
   ['id' => 79, 'domain_id' => 3, 'image_id' => 79, 'post_id' => 29, 'page_id' => NULL],
   ['id' => 80, 'domain_id' => 3, 'image_id' => 80, 'post_id' => 30, 'page_id' => NULL],
   ['id' => 81, 'domain_id' => 3, 'image_id' => 81, 'post_id' => 31, 'page_id' => NULL],
   ['id' => 82, 'domain_id' => 3, 'image_id' => 82, 'post_id' => 32, 'page_id' => NULL],
   ['id' => 83, 'domain_id' => 3, 'image_id' => 83, 'post_id' => 33, 'page_id' => NULL],
   ['id' => 84, 'domain_id' => 3, 'image_id' => 84, 'post_id' => 34, 'page_id' => NULL],
   ['id' => 85, 'domain_id' => 3, 'image_id' => 85, 'post_id' => 35, 'page_id' => NULL],
   ['id' => 86, 'domain_id' => 3, 'image_id' => 86, 'post_id' => 36, 'page_id' => NULL],
   ['id' => 87, 'domain_id' => 3, 'image_id' => 87, 'post_id' => 37, 'page_id' => NULL],
   ['id' => 88, 'domain_id' => 3, 'image_id' => 88, 'post_id' => 38, 'page_id' => NULL],
   ['id' => 89, 'domain_id' => 3, 'image_id' => 89, 'post_id' => 39, 'page_id' => NULL],
   ['id' => 90, 'domain_id' => 3, 'image_id' => 90, 'post_id' => 40, 'page_id' => NULL],
   ['id' => 91, 'domain_id' => 3, 'image_id' => 91, 'post_id' => 41, 'page_id' => NULL],
   ['id' => 92, 'domain_id' => 3, 'image_id' => 92, 'post_id' => 42, 'page_id' => NULL],
   ['id' => 93, 'domain_id' => 3, 'image_id' => 93, 'post_id' => 43, 'page_id' => NULL],
   ['id' => 94, 'domain_id' => 3, 'image_id' => 94, 'post_id' => 44, 'page_id' => NULL],
   ['id' => 95, 'domain_id' => 3, 'image_id' => 95, 'post_id' => 45, 'page_id' => NULL],
   ['id' => 96, 'domain_id' => 3, 'image_id' => 96, 'post_id' => 46, 'page_id' => NULL],
   ['id' => 97, 'domain_id' => 3, 'image_id' => 97, 'post_id' => 47, 'page_id' => NULL],
   ['id' => 98, 'domain_id' => 3, 'image_id' => 98, 'post_id' => 48, 'page_id' => NULL],
   ['id' => 99, 'domain_id' => 3, 'image_id' => 99, 'post_id' => 49, 'page_id' => NULL],
   ['id' => 100, 'domain_id' => 3, 'image_id' => 100, 'post_id' => 50, 'page_id' => NULL],
   ['id' => 101, 'domain_id' => 3, 'image_id' => 101, 'post_id' => 1, 'page_id' => NULL],
   ['id' => 102, 'domain_id' => 3, 'image_id' => 102, 'post_id' => 2, 'page_id' => NULL],
   ['id' => 103, 'domain_id' => 3, 'image_id' => 103, 'post_id' => 3, 'page_id' => NULL],
   ['id' => 104, 'domain_id' => 3, 'image_id' => 104, 'post_id' => 4, 'page_id' => NULL],
   ['id' => 105, 'domain_id' => 3, 'image_id' => 105, 'post_id' => 5, 'page_id' => NULL],
   ['id' => 106, 'domain_id' => 3, 'image_id' => 106, 'post_id' => 6, 'page_id' => NULL],
   ['id' => 107, 'domain_id' => 3, 'image_id' => 107, 'post_id' => 7, 'page_id' => NULL],
   ['id' => 108, 'domain_id' => 3, 'image_id' => 108, 'post_id' => 8, 'page_id' => NULL],
   ['id' => 109, 'domain_id' => 3, 'image_id' => 109, 'post_id' => 9, 'page_id' => NULL],
   ['id' => 110, 'domain_id' => 3, 'image_id' => 110, 'post_id' => 10, 'page_id' => NULL],
   ['id' => 111, 'domain_id' => 3, 'image_id' => 111, 'post_id' => 11, 'page_id' => NULL],
   ['id' => 112, 'domain_id' => 3, 'image_id' => 112, 'post_id' => 12, 'page_id' => NULL],
   ['id' => 113, 'domain_id' => 3, 'image_id' => 113, 'post_id' => 13, 'page_id' => NULL],
   ['id' => 114, 'domain_id' => 3, 'image_id' => 114, 'post_id' => 14, 'page_id' => NULL],
   ['id' => 115, 'domain_id' => 3, 'image_id' => 115, 'post_id' => 15, 'page_id' => NULL],
   ['id' => 116, 'domain_id' => 3, 'image_id' => 116, 'post_id' => 16, 'page_id' => NULL],
   ['id' => 117, 'domain_id' => 3, 'image_id' => 117, 'post_id' => 17, 'page_id' => NULL],
   ['id' => 118, 'domain_id' => 3, 'image_id' => 118, 'post_id' => 18, 'page_id' => NULL],
   ['id' => 119, 'domain_id' => 3, 'image_id' => 119, 'post_id' => 19, 'page_id' => NULL],
   ['id' => 120, 'domain_id' => 3, 'image_id' => 120, 'post_id' => 20, 'page_id' => NULL],
   ['id' => 121, 'domain_id' => 3, 'image_id' => 121, 'post_id' => 21, 'page_id' => NULL],
   ['id' => 122, 'domain_id' => 3, 'image_id' => 122, 'post_id' => 22, 'page_id' => NULL],
   ['id' => 123, 'domain_id' => 3, 'image_id' => 123, 'post_id' => 23, 'page_id' => NULL],
   ['id' => 124, 'domain_id' => 3, 'image_id' => 124, 'post_id' => 24, 'page_id' => NULL],
   ['id' => 125, 'domain_id' => 3, 'image_id' => 125, 'post_id' => 25, 'page_id' => NULL],
   ['id' => 126, 'domain_id' => 3, 'image_id' => 126, 'post_id' => 26, 'page_id' => NULL],
   ['id' => 127, 'domain_id' => 3, 'image_id' => 127, 'post_id' => 27, 'page_id' => NULL],
   ['id' => 128, 'domain_id' => 3, 'image_id' => 128, 'post_id' => 28, 'page_id' => NULL],
   ['id' => 129, 'domain_id' => 3, 'image_id' => 129, 'post_id' => 29, 'page_id' => NULL],
   ['id' => 130, 'domain_id' => 3, 'image_id' => 130, 'post_id' => 30, 'page_id' => NULL],
   ['id' => 131, 'domain_id' => 3, 'image_id' => 131, 'post_id' => 31, 'page_id' => NULL],
   ['id' => 132, 'domain_id' => 3, 'image_id' => 132, 'post_id' => 32, 'page_id' => NULL],
   ['id' => 133, 'domain_id' => 3, 'image_id' => 133, 'post_id' => 33, 'page_id' => NULL],
   ['id' => 134, 'domain_id' => 3, 'image_id' => 134, 'post_id' => 34, 'page_id' => NULL],
   ['id' => 135, 'domain_id' => 3, 'image_id' => 135, 'post_id' => 35, 'page_id' => NULL],
   ['id' => 136, 'domain_id' => 3, 'image_id' => 136, 'post_id' => 36, 'page_id' => NULL],
   ['id' => 137, 'domain_id' => 3, 'image_id' => 137, 'post_id' => 37, 'page_id' => NULL],
   ['id' => 138, 'domain_id' => 3, 'image_id' => 138, 'post_id' => 38, 'page_id' => NULL],
   ['id' => 139, 'domain_id' => 3, 'image_id' => 139, 'post_id' => 39, 'page_id' => NULL],
   ['id' => 140, 'domain_id' => 3, 'image_id' => 140, 'post_id' => 40, 'page_id' => NULL],
   ['id' => 141, 'domain_id' => 3, 'image_id' => 141, 'post_id' => 41, 'page_id' => NULL],
   ['id' => 142, 'domain_id' => 3, 'image_id' => 142, 'post_id' => 42, 'page_id' => NULL],
   ['id' => 143, 'domain_id' => 3, 'image_id' => 143, 'post_id' => 43, 'page_id' => NULL],
   ['id' => 144, 'domain_id' => 3, 'image_id' => 144, 'post_id' => 44, 'page_id' => NULL],
   ['id' => 145, 'domain_id' => 3, 'image_id' => 145, 'post_id' => 45, 'page_id' => NULL],
   ['id' => 146, 'domain_id' => 3, 'image_id' => 146, 'post_id' => 46, 'page_id' => NULL],
   ['id' => 147, 'domain_id' => 3, 'image_id' => 147, 'post_id' => 47, 'page_id' => NULL],
   ['id' => 148, 'domain_id' => 3, 'image_id' => 148, 'post_id' => 48, 'page_id' => NULL],
   ['id' => 149, 'domain_id' => 3, 'image_id' => 149, 'post_id' => 49, 'page_id' => NULL],
   ['id' => 150, 'domain_id' => 3, 'image_id' => 150, 'post_id' => 50, 'page_id' => NULL],
  ]);
  DB::table('efflux_site.post_tag')->insertOrIgnore([
   ['id' => 1, 'tag_id' => 5, 'post_id' => 1],
   ['id' => 2, 'tag_id' => 5, 'post_id' => 2],
   ['id' => 3, 'tag_id' => 5, 'post_id' => 3],
   ['id' => 4, 'tag_id' => 5, 'post_id' => 4],
   ['id' => 5, 'tag_id' => 5, 'post_id' => 5],
   ['id' => 6, 'tag_id' => 5, 'post_id' => 6],
   ['id' => 7, 'tag_id' => 6, 'post_id' => 7],
   ['id' => 8, 'tag_id' => 6, 'post_id' => 8],
   ['id' => 9, 'tag_id' => 6, 'post_id' => 9],
   ['id' => 10, 'tag_id' => 6, 'post_id' => 10],
   ['id' => 11, 'tag_id' => 6, 'post_id' => 11],
   ['id' => 12, 'tag_id' => 6, 'post_id' => 12],
   ['id' => 13, 'tag_id' => 6, 'post_id' => 13],
   ['id' => 14, 'tag_id' => 6, 'post_id' => 14],
   ['id' => 15, 'tag_id' => 6, 'post_id' => 15],
   ['id' => 16, 'tag_id' => 6, 'post_id' => 16],
   ['id' => 17, 'tag_id' => 6, 'post_id' => 17],
   ['id' => 18, 'tag_id' => 6, 'post_id' => 18],
   ['id' => 19, 'tag_id' => 6, 'post_id' => 19],
   ['id' => 20, 'tag_id' => 7, 'post_id' => 20],
   ['id' => 21, 'tag_id' => 7, 'post_id' => 21],
   ['id' => 22, 'tag_id' => 7, 'post_id' => 22],
   ['id' => 23, 'tag_id' => 7, 'post_id' => 23],
   ['id' => 24, 'tag_id' => 7, 'post_id' => 24],
   ['id' => 25, 'tag_id' => 7, 'post_id' => 25],
   ['id' => 26, 'tag_id' => 8, 'post_id' => 26],
   ['id' => 27, 'tag_id' => 8, 'post_id' => 27],
   ['id' => 28, 'tag_id' => 8, 'post_id' => 28],
   ['id' => 29, 'tag_id' => 8, 'post_id' => 29],
   ['id' => 30, 'tag_id' => 8, 'post_id' => 30],
   ['id' => 31, 'tag_id' => 9, 'post_id' => 31],
   ['id' => 32, 'tag_id' => 9, 'post_id' => 32],
   ['id' => 33, 'tag_id' => 9, 'post_id' => 33],
   ['id' => 34, 'tag_id' => 9, 'post_id' => 34],
   ['id' => 35, 'tag_id' => 9, 'post_id' => 35],
   ['id' => 36, 'tag_id' => 9, 'post_id' => 36],
   ['id' => 37, 'tag_id' => 9, 'post_id' => 37],
   ['id' => 38, 'tag_id' => 9, 'post_id' => 38],
   ['id' => 39, 'tag_id' => 10, 'post_id' => 39],
   ['id' => 40, 'tag_id' => 10, 'post_id' => 40],
   ['id' => 41, 'tag_id' => 10, 'post_id' => 41],
   ['id' => 42, 'tag_id' => 10, 'post_id' => 42],
   ['id' => 43, 'tag_id' => 10, 'post_id' => 43],
   ['id' => 44, 'tag_id' => 10, 'post_id' => 44],
   ['id' => 45, 'tag_id' => 10, 'post_id' => 45],
   ['id' => 46, 'tag_id' => 10, 'post_id' => 46],
   ['id' => 47, 'tag_id' => 10, 'post_id' => 47],
   ['id' => 48, 'tag_id' => 10, 'post_id' => 48],
   ['id' => 49, 'tag_id' => 10, 'post_id' => 49],
   ['id' => 50, 'tag_id' => 10, 'post_id' => 50],
   ['id' => 51, 'tag_id' => 1, 'post_id' => 44],
   ['id' => 52, 'tag_id' => 1, 'post_id' => 34],
   ['id' => 53, 'tag_id' => 1, 'post_id' => 29],
   ['id' => 54, 'tag_id' => 1, 'post_id' => 21],
   ['id' => 55, 'tag_id' => 1, 'post_id' => 18],
   ['id' => 56, 'tag_id' => 1, 'post_id' => 2],
   ['id' => 57, 'tag_id' => 2, 'post_id' => 1],
   ['id' => 58, 'tag_id' => 2, 'post_id' => 11],
   ['id' => 59, 'tag_id' => 2, 'post_id' => 39],
   ['id' => 60, 'tag_id' => 3, 'post_id' => 4],
   ['id' => 61, 'tag_id' => 3, 'post_id' => 19],
   ['id' => 62, 'tag_id' => 3, 'post_id' => 22],
   ['id' => 63, 'tag_id' => 3, 'post_id' => 30],
   ['id' => 64, 'tag_id' => 3, 'post_id' => 36],
   ['id' => 65, 'tag_id' => 3, 'post_id' => 43],
   ['id' => 66, 'tag_id' => 4, 'post_id' => 47],
   ['id' => 67, 'tag_id' => 4, 'post_id' => 25],
   ['id' => 68, 'tag_id' => 4, 'post_id' => 6],
   ['id' => 69, 'tag_id' => 6, 'post_id' => 53],
   ['id' => 70, 'tag_id' => 6, 'post_id' => 52],
   ['id' => 71, 'tag_id' => 6, 'post_id' => 51],
  ]);
 }
}