<?php

use Illuminate\Database\Seeder;

class SiteRouteSeeder extends Seeder {
 public function run() {
  DB::table('efflux_site.routes')->insertOrIgnore([
   ['id' => 1, 'status' => 1, 'uri' => 'budget-money-guide', 'post_id' => 1, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 2, 'status' => 1, 'uri' => 'find-financial-freedom', 'post_id' => 2, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 3, 'status' => 1, 'uri' => 'pick-a-realtor', 'post_id' => 3, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 4, 'status' => 1, 'uri' => 'make-money-fast', 'post_id' => 4, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 5, 'status' => 1, 'uri' => 'real-estate-investment', 'post_id' => 5, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 6, 'status' => 1, 'uri' => 'credit-building', 'post_id' => 6, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 7, 'status' => 1, 'uri' => 'fat-loss-guide', 'post_id' => 7, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 8, 'status' => 1, 'uri' => 'dangerous-diet-myths', 'post_id' => 8, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 9, 'status' => 1, 'uri' => 'lose-body-fat', 'post_id' => 9, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 10, 'status' => 1, 'uri' => 'ultramarathon-guide', 'post_id' => 10, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 11, 'status' => 1, 'uri' => 'weight-loss-guide', 'post_id' => 11, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 12, 'status' => 1, 'uri' => 'how-to-start-running', 'post_id' => 12, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 13, 'status' => 1, 'uri' => 'running-shoe-guide', 'post_id' => 13, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 14, 'status' => 1, 'uri' => 'hydrationtips', 'post_id' => 14, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 15, 'status' => 1, 'uri' => 'tracking-calories', 'post_id' => 15, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 16, 'status' => 1, 'uri' => 'meal-prep-tips', 'post_id' => 16, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 17, 'status' => 1, 'uri' => 'starting-crossfit', 'post_id' => 17, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 18, 'status' => 1, 'uri' => 'alternative-weight-loss', 'post_id' => 18, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 19, 'status' => 1, 'uri' => 'new-gym-guide', 'post_id' => 19, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 20, 'status' => 1, 'uri' => 'new-car-buyer-guide', 'post_id' => 20, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 21, 'status' => 1, 'uri' => 'car-selling-guide', 'post_id' => 21, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 22, 'status' => 1, 'uri' => 'buying-used-car', 'post_id' => 22, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 23, 'status' => 1, 'uri' => 'car-cleaning-tips', 'post_id' => 23, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 24, 'status' => 1, 'uri' => 'road-trip-tips', 'post_id' => 24, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 25, 'status' => 1, 'uri' => 'road-rage', 'post_id' => 25, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 26, 'status' => 1, 'uri' => 'influencer-guide', 'post_id' => 26, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 27, 'status' => 1, 'uri' => 'facebook-ads-guide', 'post_id' => 27, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 28, 'status' => 1, 'uri' => 'reduce-screen-time', 'post_id' => 28, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 29, 'status' => 1, 'uri' => 'podcasts', 'post_id' => 29, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 30, 'status' => 1, 'uri' => 'build-youtube-channel', 'post_id' => 30, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 31, 'status' => 1, 'uri' => 'san-diego-secrets', 'post_id' => 31, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 32, 'status' => 1, 'uri' => 'san-diego-hiking', 'post_id' => 32, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 33, 'status' => 1, 'uri' => 'airport-guide', 'post_id' => 33, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 34, 'status' => 1, 'uri' => 'vegas-most-thrilling', 'post_id' => 34, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 35, 'status' => 1, 'uri' => 'san-diego-beaches', 'post_id' => 35, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 36, 'status' => 1, 'uri' => 'hiking-gear-buyers-guide', 'post_id' => 36, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 37, 'status' => 1, 'uri' => 'san-diego-outdoor-guide', 'post_id' => 37, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 38, 'status' => 1, 'uri' => 'best-of-milwaukee', 'post_id' => 38, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 39, 'status' => 1, 'uri' => 'find-a-job', 'post_id' => 39, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 40, 'status' => 1, 'uri' => 'starting-yoga', 'post_id' => 40, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 41, 'status' => 1, 'uri' => 'mattress-buyer-guide', 'post_id' => 41, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 42, 'status' => 1, 'uri' => 'start-a-blog', 'post_id' => 42, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 43, 'status' => 1, 'uri' => 'first-date-advice', 'post_id' => 43, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 44, 'status' => 1, 'uri' => 'how-to-win-in-vegas', 'post_id' => 44, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 45, 'status' => 1, 'uri' => 'build-a-resume', 'post_id' => 45, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 46, 'status' => 1, 'uri' => 'sobriety-tips', 'post_id' => 46, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 47, 'status' => 1, 'uri' => 'interview-tips', 'post_id' => 47, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 48, 'status' => 1, 'uri' => 'morning-routine', 'post_id' => 48, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 49, 'status' => 1, 'uri' => 'find-a-relationship', 'post_id' => 49, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 50, 'status' => 1, 'uri' => 'moving-guide', 'post_id' => 50, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 51, 'status' => 1, 'uri' => 'terms', 'post_id' => NULL, 'page_id' => 2, 'domain_id' => 3],
   ['id' => 55, 'status' => 1, 'uri' => 'privacy', 'post_id' => NULL, 'page_id' => 3, 'domain_id' => 3],
   ['id' => 56, 'status' => 1, 'uri' => 'about', 'post_id' => NULL, 'page_id' => 4, 'domain_id' => 3],
   ['id' => 57, 'status' => 1, 'uri' => 'copyright', 'post_id' => NULL, 'page_id' => 5, 'domain_id' => 3],
   ['id' => 58, 'status' => 1, 'uri' => 'dentalimplants', 'post_id' => 52, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 59, 'status' => 1, 'uri' => 'copdriskfactors', 'post_id' => 51, 'page_id' => NULL, 'domain_id' => 3],
   ['id' => 60, 'status' => 1, 'uri' => 'psoriasissymptoms', 'post_id' => 53, 'page_id' => NULL, 'domain_id' => 3],
  ]);
 }
}